### ISSUE TITLE
fyi -- wcpatch.exe detected by Windows Defender as Trojan:Win32/Wacatac.C!ml

### ISSUE THREAD

**Issue by sharygin** [Bekenn/wcdx#1]
not sure if this is a known issue but didn't see in the readme. FYI.

**Comment by Bekenn** [comment]
Thanks for letting me know.  Which version of the executable is being flagged?

**Comment by sharygin** [comment]
came from wcdx-2.0-alpha2.zip downloaded last week from https://github.com/Bekenn/wcdx/releases

**Comment by Bekenn** [comment]
Is this still an issue with [release 2.2](https://github.com/Bekenn/wcdx/releases/tag/2.2)?

**Comment by sharygin** [comment]
appears resolved, no warning when unpacking new release and applying patch..
