### ISSUE TITLE
Can't launch WCDX on non-SSE2 processor

### ISSUE THREAD

**Issue by JubalHarshaw** [Bekenn/wcdx#4]
Hello, just wanted to report that I can't launch WCDX on a non-SSE2 processor (tested an AMD Sempron and Intel Celeron, both running Windows XP, nVidia GeForce 5200/5500). Original Kilrathi Saga executable works fine. (But then I wouldn't get your music fix, planets fix, and the poster! :) )

Appreciate all your hard work on this (it works beautifully on my more modern Win10 system)!

**Comment by Bekenn** [comment]
Thanks for the report!  Is there a specific error message?  I don't have an appropriate system for testing; do you feel comfortable making changes yourself?  Otherwise, I could try sending you binaries for testing.

**Comment by JubalHarshaw** [comment]
Standard "has encountered a problem and needs to close", error report signature wcdx.dll offset: 0000351a ... exception information code 0x000001d (I can get further info off the error windows or possibly screenshots). Happy to test binaries.

**Comment by Bekenn** [comment]
Try this one: [wcdx-nosse.zip](https://github.com/Bekenn/wcdx/files/6174503/wcdx-nosse.zip)

**Comment by JubalHarshaw** [comment]
Thanks, that .DLL did the trick! Success on both machines. Thanks so much! It's been a real adventure getting some stuff going on these old machines. I really appreciate this and your immediate turnaround time! You're a class act!

**Comment by Bekenn** [comment]
Glad that helped!  I'll be sure and incorporate the change into future releases.
